---
title: "Comics WOZ analysis"
output: html_notebook
---
```{r}
#libraries
library(ggplot2)
library(car)
library(dplyr)
library(reshape2)
library(pwr)
library(irr)
library(coin)
```

```{r}
comics_data <- read.table("data.csv",header=TRUE,sep=",")
head(comics_data)
```
Each row is split into condition according to which comic was shown as "Comic A" in each pair. For OrderReversed=TRUE, the adaptive (wizard) comic was shown first; the opposite is true for for OrderReversed=FALSE. Each measure is assigned a 1 or 0 depending if comic A was chosen as the preferred comic for the measure.
```{r}
comics_data <- group_by(comics_data,condition)
aggregate <- summarise(comics_data,
                       n = length(condition),
                       v_clarity=length(which(vclarity==1))/length(condition),
                       v_creativity = length(which(vcreativity==1))/length(condition),
                       n_clarity = length(which(nclarity==1))/length(condition),
                       n_creativity = length(which(ncreativity==1))/length(condition),
                       all = length(which(overall==1))/length(condition))

aggregate
```
```{r}
vclarity <- table(comics_data$condition,comics_data$vclarity)
chisq.test(vclarity, correct=FALSE)

vcreativity <- table(comics_data$condition,comics_data$vcreativity)
chisq.test(vcreativity,correct=FALSE)

nclarity <- table(comics_data$condition,comics_data$nclarity)
chisq.test(nclarity,correct=FALSE)

ncreativity <- table(comics_data$condition,comics_data$ncreativity)
chisq.test(ncreativity,correct=FALSE)

overall <- table(comics_data$condition,comics_data$overall)
chisq.test(overall,correct=FALSE)
```

```{r}
vclarity_glm <- glm(vclarity ~ condition + story, data=comics_data, family="binomial")
summary(vclarity_glm)
```
```{r}
vcreativity_glm <- glm(vcreativity ~ condition + story, data=comics_data, family="binomial")
summary(vcreativity_glm)
```
```{r}
nclarity_glm <- glm(nclarity ~ condition + story, data=comics_data, family="binomial")
summary(nclarity_glm)
```
```{r}
ncreativity_glm <- glm(ncreativity ~ condition + story, data=comics_data, family="binomial")
summary(ncreativity_glm)
```
```{r}
overall_glm <- glm(overall ~ condition + story, data=comics_data, family="binomial")
summary(overall_glm)
```
```{r}
interactions <- read.table("interactions.csv",sep=",", header=TRUE)
head(interactions)
```
```{r}
interactions <- group_by(interactions,condition)
int_aggregate <- summarise(interactions,
                       n = length(condition),
                       mean_suggestions=mean(num_suggestions),
                       mean_examples_viewed = mean(num_examples),
                       sd_examples = sd(num_examples),
                       mean_examples_used = mean(num_examples_used),
                       sd_examples_used = sd(num_examples_used),
                       mean_drawing_help = mean(num_drawing_help),
                       sd_drawing_help = sd(num_drawing_help))

int_aggregate
```

```{r}
#number of examples viewed
t.test(interactions$num_examples[interactions$condition=="woz"],interactions$num_examples[interactions$condition=="control"])

#number of times drawing helper used
t.test(interactions$num_drawing_help[interactions$condition=="woz"],interactions$num_drawing_help[interactions$condition=="control"])

```
```{r}
irr <- read.table("irr.csv",sep=",",header=TRUE)
head(irr)
```
```{r}
kripp.alpha(as.matrix(irr))
```

